#!/bin/sh
delim(){
	echo "/"
}

status () {
	# ibus engine
	echo ""
	[ $(ibus engine) = "Bamboo" ] && echo "VN" || echo "EN"
	delim

	# network 
	echo "直"
	nmcli | grep 'connected to' | sed 's/.*: connected to //g'
	grep "^\s*w" /proc/net/wireless | awk '{ print "(" int($0 * 100 / 70) "%)"}'
	delim

	# audio
	amixer sget Master | grep '\[on\]' | tail -n 1 | grep '[[:digit:]]*%' -o | awk '{ print " " $0 }'

	amixer sget Master | tail -n 1 | grep -o off | tr '[:lower:]' '[:upper:]' | awk '{print " " $0}'

	delim
	# echo "Mic:"
	# amixer sget Capture | tail -n 1 | sed 's/^ *//g' | cut -d ' ' -f 6 | grep -o 'on\|off'
	# delim

	# brightness
	echo " $(light | cut -d '.' -f 1)%"
	delim

	# battery
	# Will show all batteries with approximate icon for remaining power.
	for x in /sys/class/power_supply/BAT?/capacity;
	do
	case "$(cat $x)" in
		100|9[0-9])	echo "⚡ $(cat $x)%" ;;
		8[0-9]|7[0-9])	echo "⚡ $(cat $x)%" ;;
		6[0-9]|5[0-9])	echo "⚡ $(cat $x)%" ;;
		4[0-9]|3[0-9])	echo "⚡ $(cat $x)%" ;;
		*)		echo "⚡ $(cat $x)%" ;;
	esac
	done 
	echo "(`acpi | cut -d ' ' -f 3 | sed 's/,//' | tr '[:lower:]' '[:upper:]'`)"
	delim

	# datetime
	echo ""
	date "+%d/%m/%Y %H:%M"

}

while [ true ]
do
	status | tr "\n" " "
	# vollv=$(amixer get Master | grep Left: | grep -o '[[:digit:]]*%')
	# volon=$(amixer get Master | grep Left: | grep -o '\[on\]')
	# [ -z $volon ] && vol="volume muted" || vol="volume: $vollv" 
	# echo "$networkicon $networkssid | $ibus | $light |  $vol | $date "
	sleep 60
done

